title: Naima Munir
logo: /assets/Naima_picture_job.png
description: I am passionate about discovering trends and information hidden in data and transform it into a story to help people make better, well informed and impactful decisions. I believe data driven decisions can help solve many of our global issues and bring about a positive change. I am also particularly interested in using data insights for forecasting and predicting future trends using ML models.
show_downloads: true
theme: jekyll-theme-minimal
