title: Naima Munir
logo: /assets/Naima_picture_job_cropped.png
description: I am passionate about discovering trends and information hidden in data and transform it into a story to help people make better, well informed and impactful decisions. I am also particularly interested in using data insights for forecasting and predicting future trends using ML models.
#show_downloads: true
linkedin: naimamunir
#theme: jekyll-theme-minimal
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

#<script src="http://code.jquery.com/jquery-1.4.2.min.js"></script> <script> var x = document.getElementsByClassName("site-footer-credits"); setTimeout(() => { x[0].remove(); }, 10); </script>
